### ISSUE TITLE
Sonarr/Mp4 automator bug?

### ISSUE THREAD

**Issue by kinv** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#550]
**Describe the bug**
Error in sonarr/mp4 automator script? File permissions/directories?

Also note I also receive an error when trying to manually use mp4 automator, Invalid argument (name of file) I kind of assumed this is something I did wrong or because it doesn't like spaces in file names. May be related

**To Reproduce**
1. Download file in sonarr/mp4 automator
2. check logs?

**What is affected by this bug?**
I think I is file permissions or paths?

**When does this occur?**
Whenever nzbget hands sonarr/mp4 a file. above error log then skips proces

**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu 18.04
  * Plexguide Version: 6.49 Stable
  * Plexguide Server Type: Remote Dedi
  * Plexguide Edition: Gdrive
  * Plexguide Mount System: PGBlitz
  * Using Traefik: Yes
  * Domain DNS Provider:GoDaddy/

**Logs**
[Error] postSonarr.py: Traceback (most recent call last): 

[Error] postSonarr.py:   File "/sickbeard_mp4_automator/postSonarr.py", line 23, in <module> 

[Error] postSonarr.py:     fileConfig(os.path.join(os.path.dirname(sys.argv[0]), 'logging.ini'), defaults={'logfilename': os.path.join(logpath, 'index.log')}) 

[Error] postSonarr.py:   File "/usr/lib/python2.7/logging/config.py", line 85, in fileConfig 

[Error] postSonarr.py:     handlers = _install_handlers(cp, formatters) 

[Error] postSonarr.py:   File "/usr/lib/python2.7/logging/config.py", line 163, in _install_handlers 

[Error] postSonarr.py:     h = klass(*args) 

[Error] postSonarr.py:   File "/usr/lib/python2.7/logging/handlers.py", line 117, in __init__ 

[Error] postSonarr.py:     BaseRotatingHandler.__init__(self, filename, mode, encoding, delay) 

[Error] postSonarr.py:   File "/usr/lib/python2.7/logging/handlers.py", line 64, in __init__ 

[Error] postSonarr.py:     logging.FileHandler.__init__(self, filename, mode, encoding, delay) 

[Error] postSonarr.py:   File "/usr/lib/python2.7/logging/__init__.py", line 913, in __init__ 

[Error] postSonarr.py:     StreamHandler.__init__(self, self._open()) 

[Error] postSonarr.py:   File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open 

[Error] postSonarr.py:     stream = open(self.baseFilename, self.mode) 

[Error] postSonarr.py: IOError: [Errno 13] Permission denied: '/var/log/sickbeard_mp4_automator/index.log' 

**Additional context**
Sorry this isn't very detailed, I'm not really sure what i am doing lol. I fully expect a more savvy member to tell me I have done something wrong in the setup. Thanks

**EDIT**
I tried to edit file permissions to 775 and chown to 1000:1000 of this dir /var/log/sickbeard_mp4_automator/ as it is a permission denied error, I know the file must exist somewhere as I have got into the file to manually try and process the script, however that was from inside docker files. Possibly the dir /var/log/sickbeard_mp4_automator/ is wrong and it should be pointing elsewhere?

**Comment by kinv** [comment]
fresh install and using 6.048 rather than .51 has fixed this issue. Only now It is uploading 3 versions of the same file for some reason lol.
