### ISSUE TITLE
Update to 6.088

### ISSUE THREAD

**Issue by Sc4nd4l** [Admin9705/PlexGuide.com-The-Awesome-Plex-Server#667]
**Describe the bug**
Python / Pip error when updating to 6.088

**To Reproduce**
Update to 6.088 from a earlier version. 

**Expected behavior**
Update should be installed without any errors. 

**Screenshots**
-

**What is affected by this bug?**
Updating to 6.088
**When does this occur?**
When trying to update to 6.088
**Please tell us about your environment: (REPLACE EXAMPLE VALUES BELOW WITH YOUR ACTUAL VALUES)**
  
  * Operating System: Ubuntu [16.04]
  * Plexguide Version: 6.088 [Stable]
  * Plexguide Server Type: [Remote Dedi]
  * Plexguide Edition: [Gdrive]
  * Plexguide Mount System: [PGBlitz]
  * Using Traefik: [No]
  * Domain DNS Provider:[CloudFlare/DuckDNS/Gandi/GoDaddy/NameCheap]

**Logs**
`Usage:   
  pip list [options]

no such option: --format

Standby - Installing: PG Interface v0.0.3

Collecting git+git://github.com/Admin9705/plexguide-menu.git
  Cloning git://github.com/Admin9705/plexguide-menu.git to /tmp/pip-NYZOP_-build
  Requirement already satisfied (use --upgrade to upgrade): plexguide-menu===0.0.3 from git+git://github.com/Admin9705/plexguide-menu.git in /usr/local/lib/python2.7/dist-packages
Traceback (most recent call last):
  File "/opt/plexguide/menu/interface/install/scripts/alias.py", line 24, in <module>
    from consolemenu import *
ImportError: No module named 'consolemenu'
Traceback (most recent call last):
  File "/opt/plexguide/menu/interface/install/scripts/folders.py", line 24, in <module>
    from consolemenu import *
ImportError: No module named 'consolemenu'

Usage:   
  pip list [options]

no such option: --format

Standby - Installing: PG Interface v0.0.3

Collecting git+git://github.com/Admin9705/plexguide-menu.git
  Cloning git://github.com/Admin9705/plexguide-menu.git to /tmp/pip-OZmp7z-build
  Requirement already satisfied (use --upgrade to upgrade): plexguide-menu===0.0.3 from git+git://github.com/Admin9705/plexguide-menu.git in /usr/local/lib/python2.7/dist-packages
Traceback (most recent call last):
  File "/opt/plexguide/menu/interface/start/start.py", line 29, in <module>
    from consolemenu import *
ImportError: No module named 'consolemenu'`

**Additional context**

**Comment by Admin9705** [comment]
i'll double check. good move with hertzner cloud

**Comment by Admin9705** [comment]
![image](https://user-images.githubusercontent.com/24727006/47759272-3acbdc80-dc85-11e8-85a9-864b98b1fde7.png)

Just ran on a clean hertzner box on 18. might be a 16 issue.

**Comment by Admin9705** [comment]
tested on 16 on hertzner cloud and not getting this issue. continues to install

**Comment by Sc4nd4l** [comment]
Hi, 
Thanks for checking it out! Then its very wierd that it does not work on this Hetzner box already running PG 6.083.
